### ISSUE TITLE
Partial automation of infrastructure provisioning using terraform

### ISSUE THREAD

**Issue by divyenduz** [divyenduz/badal#1]
**Current status:**
                                  
                        ┌─────────────────┐    ┌────────────────────────┐
                        │                 │    │                        │
                        │                 │    │                        │
                        │   Elastic IP    ├────▶   EC2 with app + DB    │
                        │                 │    │                        │
                        │                 │    │                        │
                        └─────────────────┘    └────────────────────────┘

**Target status:**
                                                                         
                        ┌─────────────────┐    ┌────────────────────────┐
                        │                 │    │                        │
                        │                 │    │                        │
                        │      ELB        ├────▶   Cattle EC2s with     │
                        │                 │    │   stateless apps       │
                        │                 │    │                        │
                        └─────────────────┘    └────────────┬───────────┘
                                                            │            
                                               ┌────────────▼───────────┐
                                               │                        │
                                               │        Database        │
                                               │                        │
                                               │                        │
                                               └────────────────────────┘

**Notes:**

1. The web domains will have to point to the ELB IP after the migration from the existing Elastic IP. 
2. The migration can be done in steps, with the switchover at the end in 1 go or canary (strategy to decide).
3. Keys, AMIs to be used and some other stuff might be hardcoded at the moment. Need to see one time provisioning up (or upsert 😅equivalent in terraform). 
4. Currently, I have multiple apps running on various DBs powered by the same instance. I intend to port them as is, treating them as sorta a single unit. 

**Steps:** (unless marked otherwise, steps should be idempotent and complete i.e. I should be a able to stop at any step and it should add value, manual steps will be marked with **M** and I would think on how those can be automated in future)

1. - [x] Bake the AMIs with application (think about deployments already, maybe docker will help). **(M)**
-- Sadly, currently this will also bake in all the DBs (which also includes an SQLite).
2. - [x] Make an ALB (including how to provision EC2s - that's how ALB works kinda) and tell it to spin up one node as more than one node would fail (the application logic) because the EC2 instances are not stateless yet. 
3. - [x] Test stuff manually on the ALB IP address. **(M)**
4. - [ ] Move public domains to the ALB IP address. 

**PS notes:**
1. I have ALB but can't autoscale yet because EC2 is pet not cattle, it includes the state as it includes all the databases. 
2. How will I even deploy, it is one node but I need a way to ship application, it is coming from AMI at the moment. 
3. Think more about it, this setup is ultra leaky. 
4. Figure the above issues out later via another issue. 

**Reference:**

1. https://www.terraform.io/docs/enterprise/guides/recommended-practices/index.html
2. https://www.terraform.io/docs/providers/aws/index.html
3. https://www.hashicorp.com/blog/zero-downtime-updates-with-terraform
4. https://medium.com/cognitoiq/terraform-and-aws-application-load-balancers-62a6f8592bcf
5. https://charity.wtf/tag/terraform/

**Comment by sunnykrGupta** [comment]
@divyenduz  Let me know how can I help. I can contribute into AWS. I am pretty much familiar with aws anatomy. Terraform is something I want to get involved into.

**Comment by divyenduz** [comment]
The underlying infra does not exist anymore. This PR is outdated.
